
[#conventions]
== Terms and Definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*",
"*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*",
"*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this
document are to be interpreted as described in BCP 14
<<RFC2119>> <<RFC8174>> when, and only when, they appear in
all capitals, as shown here.

This document also refers to the following terms and
definitions:

Public Key Infrastructure::
As defined in <<RFC3280>>

Trusted Third Party::
As defined in <<RFC3161>>

Time-Stamp Authority::
As defined in <<RFC3161>>

Time-Stamp Token::
As defined in <<RFC3161>>

Distributed Ledger::
Various definitions of blockchain and distributed ledger technology exist,
and some of these stress different technical features.
Given the nature and scope of this document and the lack of definitional
consensus we choosed to use the term
as defined by UK Government Chief Scientific Adviser <<UK-GCSA>>
"A distributed ledger is essentially an asset database that can be shared across
a network of multiple sites, geographies or institutions. All participants within
a network can have their own identical copy of the ledger. Any changes to the
ledger are reflected in all copies in minutes, or in some cases, seconds. The
assets can be financial, legal, physical or electronic. The security and accuracy
of the assets stored in the ledger are maintained cryptographically through the
use of ‘keys’ and signatures to control who can do what within the shared ledger.
Entries can also be updated by one, some or all of the participants, according to
rules agreed by the network".

Merkle Tree::
As defined in <<Merkle>>, <<CrosbyWallach>> and<<RFC6962,2.1 of>>

Aggregation Server::
A server providing the aggregation in a Merkle Tree of digests to be timestamped.
Digests submitted for aggregation are added to a list periodically combined
into a single Merkle Tree. Then the digest at the root of that tree is timestamped
on a Distributed Ledger.

Distributed Ledger Attestation::
A Distributed Ledger (Timestamping) Attestation is a proof or a promise of timestamping
in a precise Distributed Ledger.

Calendar::
A calendar is simply a collection of Distributed Ledger Attestations.

Calendar Server::
A server providing remote access to a collection of Distributed Ledger Attestation.
