
[#main]
== DL Attestation

////
@cisba TODO: spiegare come nasce un DL

Many real-world applications wish to collect tamperevident logs for forensic purposes. This paper considers
the case of an untrusted logger, serving a number of
clients who wish to store their events in the log, and
kept honest by a number of auditors who will challenge
the logger to prove its correct behavior. We propose
semantics of tamper-evident logs in terms of this auditing
process. The logger must be able to prove that individual
logged events are still present, and that the log, as seen
now, is consistent with how it was seen in the past. To
accomplish this efficiently, we describe a tree-based data
structure that can generate such proofs with logarithmic
size and space, improving over previous linear constructions. Where a classic hash chain might require an
800 MB trace to prove that a randomly chosen event is in
a log with 80 million events, our prototype returns a 3 KB
proof with the same semantics. We also present a flexible
mechanism for the log server to present authenticated
and tamper-evident search results for all events matching
a predicate. This can allow large-scale log servers to
selectively delete old events, in an agreed-upon fashion,
while generating efficient proofs that no inappropriate
events were deleted. We describe a prototype implementation and measure its performance on an 80 million
event syslog trace at 1,750 events per second using a
single CPU core. Performance improves to 10,500 events
per second if cryptographic signatures are offloaded,
corresponding to 1.1 TB of logging throughput per week.

////

=== Aggregation Server
=== Calendar Server
=== OpenTimeStamps



== DL Extension of TST

Il timestamp di tipo opentimestamps (basato su blockchain) dovrà essere generato
tramite l’utilizzo di un calendar server e inserito come estensione non critica
all’interno di un timestamp che segue lo standard <<RFC3161>>.

L’aggiunta dell’estensione non critica rende il timestamp finale retro-compatibile
con i software di verifica attualmente disponibili.

L’estensione deve rispettare le indicazioni riportate in <<RFC3161>> e <<RFC3280,4.2.1 of>>.

Gli OID delle nuove estensioni avranno la seguente radice:

    id-ce-opentimestamps   OBJECT IDENTIFIER ::= { id-ce 99 }

dove id-ce identifica la radice delle estensioni standard vedi <<RFC3280>>.

=== OpenTimestamps Promise

Questa estensione rappresenta la “promessa” restituita dal calendar server in risposta alla richiesta di marcatura di un hash. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-promise OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 1 }

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        otsPromise       [1] OtsPromise }

    OtsPromise ::= OCTET STRING


==== OpenTimestamps Proof

Questa estensione rappresenta la “prova” restituita dal calendar server in risposta alla richiesta di upgrade di una promessa precedentemente ricevuta. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-proof OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 2 }

    Proof ::= SEQUENCE {
          version        [0] INTEGER,
          otsProof       [1] OtsProof,
          blockchain     [2] UTF8String }

    OtsProof ::= OCTET STRING


[#code-snippets]
=== Code snippets

Code snippets should be wrapped with `<CODE BEGINS>` and
`<CODE ENDS>` blocks, as required by the IETF Trust Legal
Provisions (TLP) <<IETF.TLP,4 parens>> specified in <<RFC5378>>.
