
[#main]
== DL Time-Stamp

=== Blocks and Transactions
=== Merkle Trees and Aggregation
=== Calendar Servers

== OpenTimestamps

Il timestamp di tipo opentimestamps (basato su blockchain) dovrà essere generato
tramite l’utilizzo di un calendar server e inserito come estensione non critica
all’interno di un timestamp che segue lo standard <<RFC3161>>.

L’aggiunta dell’estensione non critica rende il timestamp finale retro-compatibile
con i software di verifica attualmente disponibili.

L’estensione deve rispettare le indicazioni riportate in <<RFC3161>> e <<RFC3280,4.2.1 of>>.

Gli OID delle nuove estensioni avranno la seguente radice:

    id-ce-opentimestamps   OBJECT IDENTIFIER ::= { id-ce 99 }

dove id-ce identifica la radice delle estensioni standard vedi <<RFC3280>>.

=== OpenTimestamps Promise

Questa estensione rappresenta la “promessa” restituita dal calendar server in risposta alla richiesta di marcatura di un hash. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-promise OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 1 }

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        otsPromise       [1] OtsPromise }

    OtsPromise ::= OCTET STRING


==== OpenTimestamps Proof

Questa estensione rappresenta la “prova” restituita dal calendar server in risposta alla richiesta di upgrade di una promessa precedentemente ricevuta. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-proof OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 2 }

    Proof ::= SEQUENCE {
          version        [0] INTEGER,
          otsProof       [1] OtsProof,
          blockchain     [2] UTF8String }

    OtsProof ::= OCTET STRING


[#code-snippets]
=== Code snippets

Code snippets should be wrapped with `<CODE BEGINS>` and
`<CODE ENDS>` blocks, as required by the IETF Trust Legal
Provisions (TLP) <<IETF.TLP,4 parens>> specified in <<RFC5378>>.
