
[#main]
== DL Attestation

A Digital Ledger can be seen as an untrusted logger - serving a number of
clients who wish to store their events in the log -
kept honest by a number of auditors who will challenge
the logger to prove its correct behavior <<CrosbyWallach>>.

A Merkle Tree data structure accomplishes this in a very efficient way by aggregating
many requests and submitting periodically to the log only the root digest of the tree.
This log is built as a hash chain (aka blockchain) of small blocks of data.
Consequently, the entire chain can be shared and maintained
by a large number of nodes, becoming a distributed system.

In a permissioned DL the number of nodes can be small enough to permit a quick
synchronization and reach consensus concerning the state of the chain.
In a permissionless DL the large number of nodes introduces a relevant delay
in order to reach consensus.

In the case of Bitcoin, consensus is reached statistically.
Usually in an average elapsed time of one hour six new blocks are added to the chain.
A block of data that was added before the last six blocks, is considered to be practically immutable.
This is due to the high computational power that would be required to rewrite the chain.

As a result of this scenario the elapsed time - from the request of aggregation of a digest
to the proof consolidated inside the DL, may amount to one hour or more.

This is why we distinguish between a *promise* of attestation and a *proof* of attestation.
Generally, an Aggregation Server provides only a promise to timestamp the client's digest
in the DL. However, when the aggregation is completed and the Merkle Tree root hash recorded in a block within the chain, the promise has not yet been confirmed.

Only when the consensus on that block is reached - statistically, in the Bitcoin case - then
the attestation could be considered a proof, stored and provided by a Calendar Server.

For simplicity of implementation, the Aggregation and the Calendar Server can be a unique instance.
So in this document we will refer generically to a Calendar Server indicating both services.

The DLA data structure is out of scope of this specification. Any Calendar Server can define his application protocol and data structure. For this specification the DLA is considered as pure data.
