
== DL Time-Stamp Extension

A DLA, generated by a Calendar Server, MAY be included
into a TST, using a non critical extension <<RFC3161>>.

The use of non critical extension is backward compatible with currently available existing software.

The extension MUST be compliant to the specifications described in <<RFC3161,RFC 3161>> and Section 4.2.1 of <<RFC5280,RFC 5280>>.

The new extension MUST have the following root OID:

    id-ce-dlts OBJECT IDENTIFIER ::= { id-ce TBD1 }

where id-ce identify the root of standard extensions as described in <<RFC5280,RFC 5280>>.

A TST MUST NOT have more than one DL extension. This limitation is a consequence of the DL promise generation process (see <<promise_generation_process>>).

=== Promise

This extension contains the promise obtained from a Calendar Server in response to a timestamp request on the DL.
The ASN.1 structure is as follows:

    id-ce-dlts-promise OBJECT IDENTIFIER ::= { id-ce-dlts 1 }

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        dlpromise        [1] DLPromise }

    DLPromise ::= OCTET STRING

The input data, timestamped by the DLA, SHALL be the hash value of the same data that will be signed by the TSA, without the DL extension itself.

=== Proof

This extension contains the proof obtained from a Calendar Server in response to a timestamp upgrade request of a previously obtained promise.
The ASN.1 structure is as follows:

    id-ce-dlts-proof OBJECT IDENTIFIER ::= { 
        id-ce-dlts 2 }

    Proof ::= SEQUENCE {
          version        [0] INTEGER,
          dlproof        [1] DLProof,
          blockchain     [2] UTF8String }

    DLProof ::= OCTET STRING


Upgrade from a promise to a proof MAY be done requesting a new TST, including
the DL extension containing the promise previously obtained.
When the TSA receives a request containing a DL extension,
and there is a pending promise inside, it MAY request
from a Calendar Server to get the proof and MAY include it in the TST response.

[[promise_generation_process]]
=== DL Promise Generation Process

The input to the DL Promise generation process includes the result of
the message digest calculation of the DER encoded TST, without the DL extension.
If the TST contains more extensions, the hash calculation is applied to the DER
encoded TST containing all the extensions with the exclusion of the DL extension itself.

The hash algorithm and hash parameters are the same of the TST signature,
which are included in the final ContentInfo object, as described in Section 2.4.2 of <<RFC3161,RFC 3161>>.
