== DL Time-Stamp Objects

The new objects MUST have the following root OID:

    id-ce-dlts OBJECT IDENTIFIER ::= { id-ce TBD1 }

where id-ce identify the root of standard extensions as described in <<RFC5280,RFC 5280>>.

The ASN.1 structure of type Promise is as follows:

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        signerInfo       [1] issuerAndSerialNumber,
        serialNumber     [2] INTEGER,
        signature        [3] SignatureValue,
        calendarFormat   [4] UTF8String,
        dlPromise        [5] DLPromise }

    DLPromise ::= OCTET STRING

The ASN.1 structure of type Proof is as follows:

    Proof ::= SEQUENCE {
        version          [0] INTEGER,
        signerInfo       [1] issuerAndSerialNumber,
        serialNumber     [2] INTEGER,
        signature        [3] SignatureValue,
        calendarFormat   [4] UTF8String,
        dlProof          [5] DLProof }

    DLProof ::= OCTET STRING

The fields of type Promise and Proof have the following meanings:

[no-bullet]
* version is the syntax version number. It MUST always be 0.
  The usage is as described in Section 1.3 of <<RFC5652,RFC 5652>>.

* signerInfo is an IssuerAndSerialNumber type that identifies the TSU
  signing certificate as described in Section 10.2.4 of <<RFC5652,RFC 5652>>.

* serialNumber is an integer assigned by the TSA to each TimeStampToken
  as described in Section 2.4.2 of <<RFC3161,RFC 3161>>.

* signature is the field of type SignatureValue of the structure SignerInfo described
  in Section 5.3 of <<RFC5652,RFC 5652>> - not to be confused with the signerInfo field.
// FIXME: ho aggiunto questo campo per maggior chiarezza e completezza
//        tuttavia non sono sicuro che non ci siano controindicazioni

* calendarFormat is the media type format of the DL attestation.
  It MUST be a registered application media type in accordance to
  the procedures laid out in <<RFC6838,RFC 6838>>.

* dlProof is the proof obtained from a Calendar Server using the signature field as input.

* dlPromise is the promise obtained from a Calendar Server using the signature field as input.


=== DL Time-Stamp Attributes

A set of proofs or a set of promises, generated by a Calendar Server, MAY be included
into a TST, using an unsigned attribute of the per-signer information.

To grant the backward compatibility with any currently available existing software
the unsigned attribute MUST be compliant to the specifications defined
in Section 5.3 of <<RFC5652,RFC 5652>> for type Attribute.

The set of promises and the set of proofs attributes MUST be unsigned attributes;
they MUST NOT be signed attributes, authenticated attributes,
unauthenticated attributes, or unprotected attributes.

The ASN.1 structure of the set of promises attribute is as follows:

    id-ce-dlts-promises OBJECT IDENTIFIER ::= { id-ce-dlts 0 }

    Promises            SET OF Promise

The ASN.1 structure of the set of proofs attribute is as follows:

    id-ce-dlts-proofs OBJECT IDENTIFIER ::= { id-ce-dlts 1 }

    Proofs              SET OF Proof


=== DL Time-Stamp Extensions

Upgrade from a set of promises to a set of proofs MAY be done
requesting a new TST including in a non critical extension
the set of promises previously obtained inside an unsigned attribute.

When the TSA receives a request wich has a non critical extension
containing a set of promises,
it MAY request from a Calendar Server to get the corresponding proof
for each of them, and MAY include the set of proofs in the TST response
using a non critical extension of the TSTInfo sequence.

To grant the backward compatibility with any currently available existing software
the request and response non critical extensions MUST be compliant
to the specifications described in Section 2.4 of <<RFC3161,RFC 3161>>
and Section 4.2 of <<RFC5280,RFC 5280>>.

Conforming TSAs MUST mark these extensions as non-critical.

The ASN.1 structure of the proof request extension is as follows:

    id-ce-dlts-promises OBJECT IDENTIFIER

    Proomises            SET OF Promise

The ASN.1 structure of the proof response extension is as follows:

    id-ce-dlts-proofs OBJECT IDENTIFIER

    Proofs               SET OF Proof

=== Response Status

The response status code in the TimeStampResp MUST be compliant
to the specifications described in Section 2.4.2 of <<RFC3161,RFC 3161>>
and Section 5.2.3 of <<RFC4210,RFC 4210>>.

//FIXME: Siamo sicuri che non serva uno status specifico e distinto relativo agli oggetti dlts?
//       Se la TSA deve rispondere grantedWithMods per la marca PKI e granted per i dlts?
//       Non è meglio mettere un campo status dentro ogni set-of-promises e set-of-proofs?
Compliant servers SHOULD use status field as follows:

* when in the response there are all the expected proofs and promises,
  the status field MUST contain the value zero (granted).

* when in the response only a subset of the expected proofs and promises is returned,
  the status field MUST contain the value one (grantedWithMods).

* when all the received promises are not recognized by the Calendar Server
  the status field MUST contain the value two (rejection).

* when all the received promises recognized by the Calendar Server are pending
  the status field MUST contain the value three (waiting).
