
=== OTS Extension

A DLA, generated by a Calendar Server, MAY be included
into a TST compliant to <<RFC3161>> using a non critical Extension.

The non critical extension generate a TST compliant with the standard
and software currently availables.

The extension MUST follow the specifications described in <<RFC3161>> and <<RFC3280,4.2.1 of>>.

The OID of the new extension MUST have the following root:

    id-ce-opentimestamps   OBJECT IDENTIFIER ::= { id-ce 99 }

// @riba dovremmo usare un nome dell'OID non legato alla tecnologia opentimestamps
// proposta: id-ce-dlext

where id-ce identify the root of standard extensions as described in <<RFC3280>>.

////
@riba dobbiamo valutare se e come distinguere:
    * il tipo di token richiesto: parallel oppure serial
    * il tipo di richiesta: promise oppure proof/upgrade

////
=== OTS Promise

Questa estensione rappresenta la “promessa” restituita dal calendar server in risposta alla richiesta di marcatura di un hash. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-promise OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 1 }

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        otsPromise       [1] OtsPromise }

    OtsPromise ::= OCTET STRING


=== OTS Proof

Questa estensione rappresenta la “prova” restituita dal calendar server in risposta alla richiesta di upgrade di una promessa precedentemente ricevuta. Di seguito è riportata la struttura ASN.1:

    id-ce-opentimestamps-proof OBJECT IDENTIFIER ::= { 
        id-ce-opentimestamps 2 }

    Proof ::= SEQUENCE {
          version        [0] INTEGER,
          otsProof       [1] OtsProof,
          blockchain     [2] UTF8String }

    OtsProof ::= OCTET STRING


[#code-snippets]
=== Code snippets

Code snippets should be wrapped with `<CODE BEGINS>` and
`<CODE ENDS>` blocks, as required by the IETF Trust Legal
Provisions (TLP) <<IETF.TLP,4 parens>> specified in <<RFC5378>>.
