== DL Time-Stamp Objects

The new objects MUST have the following root OID:

    id-ce-dlts OBJECT IDENTIFIER ::= { id-ce TBD1 }

where id-ce identify the root of standard extensions as described in <<RFC5280,RFC 5280>>.

The ASN.1 structure of type Promise is as follows:

    Promise ::= SEQUENCE {
        version          INTEGER,
        calendarFormat   UTF8String,
        dlPromise        DLPromise,
        signerInfo       issuerAndSerialNumber,
        serialNumber     INTEGER }

    DLPromise ::= OCTET STRING


The ASN.1 structure of type Proof is as follows:

    Proof ::= SEQUENCE {
        version          INTEGER,
        calendarFormat   UTF8String,
        dlProof          DLProof,
        signerInfo       issuerAndSerialNumber,
        serialNumber     INTEGER }

    DLProof ::= OCTET STRING

The fields of type Promise and Proof have the following meanings:

[no-bullet]
* version is the syntax version number. It MUST always be 0.
  The usage is as described in Section 1.3 of <<RFC5652,RFC 5652>>.

* calendarFormat is the media type format of the DL attestation.
  It MUST be a registered application media type in accordance to
  the procedures laid out in <<RFC6838,RFC 6838>>.

* dlProof and dlPromise are the proof and the promise obtained from
  a Calendar Server using as input value the value of signature field of
  the SignerInfo structure, described in Section 5.3 of <<RFC5652,RFC 5652>>,
  of the digital signature of the TimeStampToken.

* signerInfo is an IssuerAndSerialNumber type that identifies the TSU
  signing certificate as described in Section 10.2.4 of <<RFC5652,RFC 5652>>.

* serialNumber is an integer assigned by the TSA to each TimeStampToken
  as described in Section 2.4.2 of <<RFC3161,RFC 3161>>.


=== DL Time-Stamp Attributes

A set of proofs or a set of promises, generated by a Calendar Server, MAY be included
into a TST, using an unsigned attribute of the per-signer information.

To grant the backward compatibility with any currently available existing software
the unsigned attribute MUST be compliant to the specifications defined
in Section 5.3 of <<RFC5652,RFC 5652>> for type Attribute.

The set of promises and the set of proofs attributes MUST be unsigned attributes;
they MUST NOT be signed attributes, authenticated attributes,
unauthenticated attributes, or unprotected attributes.

The ASN.1 structure of the set of promises attribute is as follows:

    id-ce-dlts-promises OBJECT IDENTIFIER ::= { id-ce-dlts 0 }

    Promises            SET OF Promise

The ASN.1 structure of the set of proofs attribute is as follows:

    id-ce-dlts-proofs OBJECT IDENTIFIER ::= { id-ce-dlts 1 }

    Proofs              SET OF Proof

All the attributes refer to the same parent TimeStampToken.
// FIXME: spiegare bene il riferimento al timestamp emesso in quel momento


==== Response Status

The response status code in the TimeStampResp MUST be compliant
to the specifications described in Section 2.4.2 of <<RFC3161,RFC 3161>>
and Section 5.2.3 of <<RFC4210,RFC 4210>>.

Compliant servers SHOULD use status field as follows:

* when in the response there are all the expected proofs and/or promises,
  the status field MUST contain the value zero (granted).

* when in the response only a subset of the expected proofs and/or promises is returned,
  the status field MUST contain the value one (grantedWithMods).
//FIXME: Supponiamo che la TSA restituisca due promesse, una su DL BTC e una su DL ETH.
//       Supponiamo che solo la promise su DL ETH fallisca per qualche motivo.
//       La TSA deve rispondere grantedWithMods ma il client ignora l'attributo unsigned.

* when in the response no proofs or promises is returned,
  the status field MUST contain the value one (rejection).

=== DL Time-Stamp Extensions

Upgrade from a set of promises to a set of proofs MAY be done
requesting a new TST including in a non critical extension
the set of promises previously obtained inside an unsigned attribute.

When the TSA receives a request which has a non critical extension
containing a set of promises,
it MAY request from a Calendar Server to get the corresponding proof
for each of them, and MAY include the set of proofs in the TST response
using a non critical extension of the TSTInfo sequence.

To grant the backward compatibility with any currently available existing software
the request and response non critical extensions MUST be compliant
to the specifications described in Section 2.4 of <<RFC3161,RFC 3161>>
and Section 4.2 of <<RFC5280,RFC 5280>>.

Conforming TSAs MUST mark these extensions as non-critical.

The ASN.1 structure of the proof request extension is as follows:

    id-ce-dlts-promises OBJECT IDENTIFIER

    Proomises            SET OF Promise

The ASN.1 structure of the proof response extension is as follows:

    id-ce-dlts-proofs OBJECT IDENTIFIER

    Proofs               SET OF Proof

All the extensions refer to other TimeStampToken, each Proof contains
an explicit reference to the pointing TimeStampToken with signerInfo
(referring to TSU certificate) and serialNumber (referring to time stamp serial number).
// FIXME: spiegare bene che non si fa mai riferimento al timestamp corrente
//        ma solo ad altri precedenti

=== Response Status

The response status code in the TimeStampResp MUST be compliant
to the specifications described in Section 2.4.2 of <<RFC3161,RFC 3161>>
and Section 5.2.3 of <<RFC4210,RFC 4210>>.

//FIXME: spiegare che lo status PKI sovrascrive quello dlts
Compliant servers SHOULD use status field as follows:

* when in the response there are all the expected proofs and/or promises,
  the status field MUST contain the value zero (granted).

* when in the response only a subset of the expected proofs is returned,
  the status field MUST contain the value one (grantedWithMods).

* when in the response no proofs or promises is returned,
  the status field MUST contain the value one (rejection).

* when all the received promises are not recognized by the Calendar Server
  the status field MUST contain the value two (rejection).

* when all the received promises recognized by the Calendar Server are pending
  the status field MUST contain the value three (waiting).
