
== DL Time-Stamp Extension

A DLA, generated by a Calendar Server, MAY be included
into a TST compliant to <<RFC3161>> using a non critical extension.

The use of non critical extension is backward compatible with software currently availables.

The extension MUST follow the specifications described in <<RFC3161>> and <<RFC5280,4.2.1 of>>.

The new extension MUST have the following root OID:

    id-ce-dlts OBJECT IDENTIFIER ::= { id-ce TBD1 }

where id-ce identify the root of standard extensions as described in <<RFC5280>>.

=== Promise

This extension contain the promise obtained from a Calendar Server in response to a timestamp request on the DL.
The ASN.1 structure is as follow:

    id-ce-dlts-promise OBJECT IDENTIFIER ::= { id-ce-dlts 1 }

    Promise ::= SEQUENCE {
        version          [0] INTEGER,
        dlpromise        [1] DLPromise }

    DLPromise ::= OCTET STRING

The data timestamped by the DLA SHALL be an hash of
the same data that will be signed by the TSA without the DL extension itself.

=== Proof

This extension contain the proof obtained from a Calendar Server in response to a timestamp upgrade request of a previously obtained promise.
The ASN.1 structure is as follow:

    id-ce-dlts-proof OBJECT IDENTIFIER ::= { 
        id-ce-dlts 2 }

    Proof ::= SEQUENCE {
          version        [0] INTEGER,
          dlproof        [1] DLProof,
          blockchain     [2] UTF8String }

    DLProof ::= OCTET STRING


The upgrade from a promise to a proof MAY be done requesting a new TST, including
the DL extension containing the promise prevously obtained.
When the TSA receive a request containing a DL extension
if there is a pending promise inside, it MAY request the Calendar Server to get the
proof and MAY include it in the new TST.
