
== DL Time-Stamp Objects

The ASN.1 structure of Promise type is as follows:

    Promise ::= SEQUENCE {
        version          INTEGER,
        calendarFormat   UTF8String,
        dlPromise        DLPromise,
        signerIdentifier issuerAndSerialNumber,
        serialNumber     INTEGER }

    DLPromise ::= OCTET STRING


The ASN.1 structure of Proof type is as follows:

    Proof ::= SEQUENCE {
        version          INTEGER,
        calendarFormat   UTF8String,
        dlProof          DLProof,
        signerIdentifier issuerAndSerialNumber,
        serialNumber     INTEGER }

    DLProof ::= OCTET STRING
----

The fields of Promise and Proof type have the following meanings:

* version is the syntax version number. It MUST always be 0.
  The usage is as described in <<RFC5652,section=1.3>>

* calendarFormat is the media type format of the DL attestation.
  It MUST be a registered application media type, in accordance with
  procedures laid out in <<RFC6838>> - for example, if you wanted
  to use the <<OpenTimestamps>> format, the calendarFormat value would be
  the string "application/vnd.opentimestamps.ots" (without quotes)
  that is the IANA registered Media Type <<OTS>>

* dlProof and dlPromise are the proof and promise obtained from a Calendar Server
  using as input value the value of the signature field of the SignerInfo structure
  inside the digital signature of the TimeStampToken, as described in
  <<RFC5652,section=5.3>>

* signerIdentifier is an IssuerAndSerialNumber type that identifies the TSU
  signing certificate as described in <<RFC5652,section=10.2.4>>

* serialNumber is an integer assigned by the TSA to each TimeStampToken
  as described in <<RFC3161,section=2.4.2>>


=== DL Time-Stamp Attributes

A set of proofs or a set of promises, generated by a Calendar Server, MAY be included
in a TST, using an unsigned attribute of the per-signer information.

To grant backward compatibility with any currently available software
the unsigned attribute MUST be compliant with the specifications defined
in <<RFC5652,section=5.3>> for Attribute type.

Attributes including a set of promises and a set of proofs MUST be unsigned attributes;
they MUST NOT be signed attributes, authenticated attributes,
unauthenticated attributes, or unprotected attributes.

The new objects MUST have the following OIDs where id-ce identifies
the root of standard extensions as described in <<RFC5280>>.

The ASN.1 structure of attributes including a set of promises is as follows:

    id-ce-dltsPromises OBJECT IDENTIFIER ::= { id-ce TBD1 }

    Promises            SET OF Promise

The ASN.1 structure of attributes including a set of proofs is as follows:

    id-ce-dltsProofs OBJECT IDENTIFIER ::= { id-ce TBD2 }

    Proofs              SET OF Proof

All the proofs and promises that have been returned MUST refer to the same parent
TimeStampToken issued at the time of the request.

Note that a TSA can return a set of proofs and promises for the same input value
as it can use calendar servers operating on different Distributed Ledgers.

==== Response Status

The response status code in the TimeStampResp MUST be compliant with
the specifications described in <<RFC3161,section=2.4.2>>
and <<RFC4210,section=5.2.3>>.

According to the TimeStamp policy, when the response contains only a subset
of the expected proofs and promises, the status field SHOULD contain either
the value one (grantedWithMods) or the value two (rejection).

=== DL Time-Stamp Extensions

Upgrade from a set of promises to a set of proofs MAY be done
requesting a new TST including inside a non critical extension
the set of promises previously obtained in an unsigned attribute.

When the TSA receives a request which has a non critical extension
containing a set of promises,
it MAY request the Calendar Server to get the corresponding proof
for each of them, and MAY include the set of proofs in the TST response,
using a non critical extension of the TSTInfo sequence.

To grant backward compatibility with any currently available software,
request and response non critical extensions MUST be compliant
with the specifications described in Section 2.4 of <<RFC3161>>
and Section 4.2 of <<RFC5280>>.

Conforming TSAs MUST mark these extensions as non-critical.

The ASN.1 structure of the proof request extension is as follows:

    id-ce-dltsPromises OBJECT IDENTIFIER

    Promises            SET OF Promise

The ASN.1 structure of the proof response extension is as follows:

    id-ce-dltsProofs OBJECT IDENTIFIER

    Proofs               SET OF Proof

The proofs returned in the extensions by the TSA MUST NOT refer to
the TimeStampToken issued at the time of the request.
Each Proof MUST contain the explicit reference to the pointing
TimeStampToken with signerIdentifier (referring to the TSU certificate)
and serialNumber (referring to the time stamp serial number),
which have been received in the Promise structure of the proof request extension.


==== Response Status

The response status code in the TimeStampResp MUST be compliant
with the specifications described in <<RFC3161,section=2.4.2>>
and <<RFC4210,section=5.2.3>>.

Compliant servers SHOULD also use the status field as follows:

* according to TimeStamp policy, when the response contains only a subset
  of the expected proofs, the status field SHOULD contain either the value one
  (grantedWithMods) or two (rejection)

* when in the response no proof can be returned,
  the status field SHOULD contain the value two (rejection)

* when all the received promises recognized by the Calendar Server are pending,
  the status field SHOULD contain the value three (waiting).

=== Use case

In order to clarify the use of the objects thus defined, the case of
a subscription made by two actors at different times, using distinct
time stamps, is illustrated below.

==== Promises

Since each signer applies a time stamp to his signature, the structure
will be presented according to the following simplified scheme, in which
each promise is inserted as an unsigned attribute of the time stamp
to which it refers.

[[use-case-promises]]
.Figure 1
====

[align=center,alt=alt_text,type=text/plain]
....
signature-1
    +--- timestampToken
                |--- signerIdentifier
                |--- serialNumber-1
                +--- id-ce-dltsPromises
                        +--- Promise
                                |--- version
                                |--- calendarFormat
                                |--- dlPromise
                                |--- signerIdentifier
                                +--- serialNumber-1
signature-2
    +--- timestampToken
                |--- signerIdentifier
                |--- serialNumber-2
                +--- id-ce-dltsPromises
                        +--- Promise
                                |--- version
                                |--- calendarFormat
                                |--- dlPromise
                                |--- signerIdentifier
                                +--- serialNumber-2
....

====

Although replicating the signerIdentifier and serialNumber information
may seem redundant in the case of a single timestamp, it can never be
ruled out that a second signature with a new timestamp will be added later.

When you also want to obtain the proof of attestation on the DL, the
application will be able to collect the two promises and include them
as extensions in a new timestamp request. The result would have the
following structure:

[[use-case-proofs]]
.Figure 2
====

[align=center,alt=alt_text,type=text/plain]
....
    +--- timestampToken
                |--- signerIdentifier
                |--- serialNumber-3
                +--- id-ce-dltsPromises
                        +--- Proof
                                |--- version
                                |--- calendarFormat
                                |--- dlPromise
                                |--- signerIdentifier
                                +--- serialNumber-1
                        +--- Proof
                                |--- version
                                |--- calendarFormat
                                |--- dlPromise
                                |--- signerIdentifier
                                +--- serialNumber-2
....

====

From this example it is evident that the signerIdentifier and serialNumber pair
is necessary to uniquely identify the TimestampToken to which each Proof
obtained refers.

It is up to the application to choose whether the new timestamp, containing
the evidence, will be saved within the same document, containing the promises,
or stored separately.
